name: WorldEditDisplay
version: '${project.version}'
main: dev.twme.worldeditdisplay.WorldEditDisplay
api-version: '1.20'
authors: [ TWME-TW ]
depend:
  - packetevents

commands:
  wedisplayreload:
    description: Reload WorldEditDisplay configuration
    usage: /wedisplayreload
    permission: worldeditdisplay.reload
    permission-message: §cYou don't have permission to use this command!
  wedisplay:
    description: Manage personal rendering settings and toggle rendering
    usage: |
      /wedisplay set <renderer> <setting> <value> - Set personal parameters
      /wedisplay reset <renderer> [setting] - Reset to server defaults
      /wedisplay show [renderer] - Show current settings
      /wedisplay reloadplayer - Reload personal settings
      /wedisplay toggle - Toggle rendering on/off
    aliases: [worldeditdisplay]

permissions:
  worldeditdisplay.use:
    description: Allow using WorldEditDisplay rendering
    default: true
  worldeditdisplay.use.settings:
    description: Allow managing personal rendering settings
    default: true
  worldeditdisplay.reload:
    description: Allow reloading WorldEditDisplay configuration
    default: op
  worldeditdisplay.render.auto-enable:
    description: Automatically enable rendering when player joins server
    default: true
